### ISSUE TITLE
找不到 search.json

### ISSUE THREAD

**Issue by yin-shu** [maple-flowers/maple-from-fall-and-flower#3]
使用最新版 sd 报错了， mac 电脑

Error loading script: main.py
Traceback (most recent call last):
  File "/Users/ys/code/stable-diffusion/stable-diffusion-webui/modules/scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/Users/ys/code/stable-diffusion/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/ys/code/stable-diffusion/stable-diffusion-webui/extensions/maple-from-fall-and-flower-main/scripts/main.py", line 86, in <module>
    with open(path+"/search.json") as search:
FileNotFoundError: [Errno 2] No such file or directory: '/search.json'

**Comment by ZhianLin** [comment]
识别不了路径，这是路径识别方式的问题，我是直接把它改成绝对路径。把main.py的低9行
`path="./extensions/maple-from-fall-and-flower/scripts"`
改成绝对路径，比如我在autodl的云端，就是改成 `path="/root/stable-diffusion-webui/extensions/maple-from-fall-and-flower-product/scripts"`

**Comment by maple-flowers** [comment]
请将最外层maple-from-fall-and-flower-main文件夹名字改为maple-from-fall-and-flower即可解决，为您带来的不便请谅解
