### ISSUE TITLE
元素法典切换魔法咒语

### ISSUE THREAD

**Issue by leo07051004** [maple-flowers/maple-from-fall-and-flower#4]
Traceback (most recent call last):
  File "D:\sd\sd-webui-aki-v4\py310\lib\site-packages\gradio\routes.py", line 414, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\sd\sd-webui-aki-v4\py310\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "D:\sd\sd-webui-aki-v4\py310\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\sd\sd-webui-aki-v4\py310\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\sd\sd-webui-aki-v4\py310\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\sd\sd-webui-aki-v4\py310\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\sd\sd-webui-aki-v4\extensions\maple-from-fall-and-flower\scripts\main.py", line 424, in cheese_to_all
    add=[(it[2] if it[2]=="" else it[2]+"&&")+tags[it[0]].get("tags")+"【"+tags[it[0]].get("chin").replace("\\n"," ")+"】【"+tags[it[0]].get("num")+"】【"+it[3]+"】—"+str(it[1])+"—" for it in file.get("add")]
AttributeError: 'NoneType' object has no attribute 'get'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

**Comment by maple-flowers** [comment]
最新版本已经修复，并添加元素法典2.5卷，感谢您的支持
